kafka:
  bootstrap-servers: 127.0.0.1:9092
  topic.request-topic: request_musica_topic
  topic.requestreply-topic: reply_musica_topic
  consumergroup: request_reply_grupo2

spring:
  application:
    name: consumer

  kafka:
    producer:
      max:
        request:
          size: 231072000
      batch-size: 60000000
      buffer-memory: 60000000
    bootstrap-servers: 127.0.0.1:9092
    client-id: consumer
    consumer:
      group-id: request_reply_grupo2
      auto-offset-reset: earliest
      enable-auto-commit: false